import {
   mdiAccount, mdiArrowLeftRight,
   mdiBellOff, mdiDelete,
   mdiDolphin,
   mdiDuck,
   mdiElephant, mdiEmoticonOutline,
   mdiFactory,
   mdiForklift,
   mdiHorse, mdiMenu,
   mdiOwl, mdiShare, mdiShareVariant, mdiShareVariantOutline,
   mdiSlashForward,
   mdiTeddyBear, mdiTrashCan,
   mdiTrayArrowDown,
} from '@mdi/js';

export const APP_ICONS = {
   industryVehicle: mdiForklift,
   strike: mdiSlashForward,
   person: mdiAccount,
   bear: mdiTeddyBear,
   dolphin: mdiDolphin,
   duck: mdiDuck,
   elephant: mdiElephant,
   horse: mdiHorse,
   owl: mdiOwl,
   manufacturer: mdiFactory,
   download: mdiTrayArrowDown,
   smile: mdiEmoticonOutline,
   share: mdiShareVariantOutline,
   menu: mdiMenu,
   disableAlerts: mdiBellOff,
   delete: mdiDelete,
   arrowLeftRight: mdiArrowLeftRight,
};
